### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Onotoko** [corelight/zeek-community-id#13]
Hi there,
I am using zeek-3.3.0, and after I complied and install zeek. 
I download zeek-communiti-id to add to zeek. but after successfully configuration (./configure) , I went to build folder then do
`make` command but unfortunately I got a message as below

```
make[2]: *** No rule to make target '/xx/zeek/build/auxil/bifcl/bifcl', needed by 'communityid.bif.h'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:189: CMakeFiles/bif-plugin-Corelight_CommunityID-communityid.bif.dir/all] Error 2

```

Any advice for me can fix it?

Thank you!

**Comment by ErdemOzgen** [comment]
Hi @Onotoko You can use following steps:
```bash
cd build
cmake --build .
sudo cmake --install .

```
I hope it helps.
