### ISSUE TITLE
Zeek 4 lts question

### ISSUE THREAD

**Issue by spicycanary91** [corelight/zeek-community-id#18]
Hello!

I recently had to upgrade from zeek-lts 3 to 4. I was wondering if this install will work anyway on 4 even so the tests fail or is it simply not compatible?

On zeek version 4.0.1

zkg install zeek/corelight/zeek-community-id
The following packages will be INSTALLED:
  zeek/corelight/zeek-community-id (3.2.0)

Proceed? [Y/n] Y
Running unit tests for "zeek/corelight/zeek-community-id"
error: "zeek/corelight/zeek-community-id" tests failed, inspect contents of /home/zeek/.zkg/testing/zeek-community-id for details, especially any "zkg.test_command.{stderr,stdout}" files within /home/zeek/.zkg/testing/zeek-community-id/clones/zeek-community-id
Proceed to install anyway? [N/y] N
Abort.

I understand that it isn't listed as supported. 

Thank you!

**Comment by spicycanary91** [comment]
Looks like it was a permission issue. My bad

**Comment by ckreibich** [comment]
@spicycanary91, no problem. 4.0.1 should indeed work fine with the latest tagged version. If the permission issue was due to something unusual that `zkg` could have made clearer, I'd love to see more details.

**Comment by cah-erich-horst** [comment]
I am experiencing the same issue as described above. Where where the permissions issues?

The following packages will be INSTALLED:
  zeek/corelight/zeek-community-id (3.2.1)

Proceed? [Y/n] 
Running unit tests for "zeek/corelight/zeek-community-id"
error: failed to run tests for zeek/corelight/zeek-community-id: package build_command failed, see log in /opt/zeek/var/lib/zkg/logs/zeek-community-id-build.log
Proceed to install anyway? [N/y] Y
Installing "zeek/corelight/zeek-community-id"..
Failed installing "zeek/corelight/zeek-community-id": package build_command failed, see log in /opt/zeek/var/lib/zkg/logs/zeek-community-id-build.log
error: incomplete installation, the follow packages failed to be installed:
  zeek/corelight/zeek-community-id (3.2.1)

**Comment by ckreibich** [comment]
When you see the `build_command failed` message, there's no point in continuing — the build process for the Zeek plugin contained in this package failed, so always take a look at the reported files. This is not a permissions problem.

I see you shared the needed details over in #20 — thanks! I'll follow up there.
