### ISSUE TITLE
Zeek 4.1.1 Install issue

### ISSUE THREAD

**Issue by cah-erich-horst** [corelight/zeek-community-id#20]
Having an identical issue that was mentioned in ticket 18 where it was claimed a permissions issue.
I am receiving failures
Running with sudo privileges
 
The following packages will be INSTALLED:
  zeek/corelight/zeek-community-id (3.2.1)

Proceed? [Y/n] 
Running unit tests for "zeek/corelight/zeek-community-id"
error: failed to run tests for zeek/corelight/zeek-community-id: package build_command failed, see log in /opt/zeek/var/lib/zkg/logs/zeek-community-id-build.log
Proceed to install anyway? [N/y] Y
Installing "zeek/corelight/zeek-community-id"..
Failed installing "zeek/corelight/zeek-community-id": package build_command failed, see log in /opt/zeek/var/lib/zkg/logs/zeek-community-id-build.log
error: incomplete installation, the follow packages failed to be installed:
  zeek/corelight/zeek-community-id (3.2.1)

Build log

=== STDOUT ===
Build Directory        : build
Zeek Source Directory  : 
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k")  
-- Performing Test cxx17_already_works
-- Performing Test cxx17_already_works - Failed
-- Configuring incomplete, errors occurred!
See also "/opt/zeek/var/lib/zkg/clones/package/zeek-community-id/build/CMakeFiles/CMakeOutput.log".
See also "/opt/zeek/var/lib/zkg/clones/package/zeek-community-id/build/CMakeFiles/CMakeError.log".

**Comment by ckreibich** [comment]
Hi! This is the crux: ` -- Performing Test cxx17_already_works - Failed`. You'll need a newer compiler suite. Try at least GCC 5, per: https://gcc.gnu.org/projects/cxx-status.html#cxx17

What distro/platform are you on?

**Comment by cah-erich-horst** [comment]
Thanks for the reply. distro is CentOS7

**Comment by ckreibich** [comment]
Cool, thanks — so hopefully that's not a big hurdle then. The newer devtoolsets (`devtoolset-7` or `devtoolset-8`, I believe) have suitably new GCC versions.
