### ISSUE TITLE
building zeek-community-id fails - const.bif.netvar_h

### ISSUE THREAD

**Issue by AntonyNow19** [corelight/zeek-community-id#22]
Hi

Im trying to install the community-id package against zeek 5.0.
I have the following error during make (same for zkg ofcourse) :

`In file included from /opt/zeek/src/zeek/zeek/zeek/iosource/Packet.h:19,
                 from /opt/zeek/src/zeek/zeek/Conn.h:20,
                 from /opt/zeek/src/zeek/zeek-bif.h:5,
                 from /root/.zkg/clones/package/zeek-community-id/build/communityid.bif.h:7,
                 from /root/.zkg/clones/package/zeek-community-id/build/communityid.bif.cc:4:
/opt/zeek/src/zeek/NetVar.h:108:10: fatal error: const.bif.netvar_h: No such file or directory
  108 | #include "const.bif.netvar_h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Corelight-CommunityID.linux-x86_64.dir/build.make:109: CMakeFiles/Corelight-CommunityID.linux-x86_64.dir/communityid.bif.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:146: CMakeFiles/Corelight-CommunityID.linux-x86_64.dir/all] Error 2
make: *** [Makefile:166: all] Error 2`

Any idea what could be the issue ?

thanks

**Comment by ckreibich** [comment]
Hi Antony — how did you install Zeek, and what's in your installation's `include/zeek` folder? There should be a `const.bif.netvar_h` file in there. If it isn't, I suspect something went wrong with the install or its packaging.

**Comment by ckreibich** [comment]
Wait — did you install? Your folders all say `/opt/zeek/src/zeek`. `const.bif.netvar_h` is a generated file, so if you're somehow using the source folder, that won't work.

**Comment by ckreibich** [comment]
Antony I'm going to close this, but holler if this is still a problem. Thanks.
