### ISSUE TITLE
Installing from bro-pkg gives an error

### ISSUE THREAD

**Issue by mrdraper** [corelight/zeek-community-id#5]
When i try to install from the package manager with:

bro-pkg install bro-community-id

I get an error stating:

Cannot determine Bro source directory, use —Bro-dist=DIR.

And the install fails. Any way around this?

My bro and bro-config PATH is set properly. Bro-pkg is version 1.5.2 and bro is 2.6.1.

**Comment by ckreibich** [comment]
Do you have a Bro source tree nearby? If you have it in, say, `~/src/bro`, try using `--bro-dist=~/src/bro` as the command suggests. This is different from the BROPATH environment variable, and has nothing to do with bro-config. The Community ID package is technically also a Bro plugin, meaning it requires the Bro sources to compile a few things.

Hope this helps...

**Comment by ckreibich** [comment]
I just realized that your problem is more likely around `bro-pkg` no longer finding your Bro tree, not directly the use of `--bro-dist`... Did you run `bro-pkg autoconfig` to bootstrap your `bro-pkg` setup, and if so, is your tree still in the place it was when you did? This should make `bro-pkg` pass the right thing to `--bro-dist` when it comes up.

https://bro-package-manager.readthedocs.io/en/stable/quickstart.html

**Comment by mrdraper** [comment]
Thanks for getting back to me!

I managed to get the install working with bro-pkg, i also loaded the plugin with bro-pkg. (`bro-pkg load bro-community-id`) However, i do not see the community-id string in my conn.log.

Output from `broctl scripts` is:
`/usr/local/bro/lib/bro/plugins/packages/bro-community-id/lib/bif/__load__.bro `
`  /usr/local/bro/lib/bro/plugins/packages/bro-community-id/lib/bif/communityid.bif.bro`
`  /usr/local/bro/lib/bro/plugins/packages/bro-community-id/scripts/__load__.bro`

The `/usr/local/bro/lib/bro/plugins/packages/bro-community-id/scripts/__load__.bro` is however empty, is this normal?

The `__load__.bro`  file (which contains the config) in`/usr/local/bro/lib/bro/plugins/packages/bro-community-id/scripts/Corelight/CommunityID` does not seem to be loaded by broctl.

**Comment by mrdraper** [comment]
If i try to load the config file i get the following errors:

`warning in /usr/local/bro/lib/bro/plugins/packages/bro-community-id/scripts/./Corelight/CommunityID//__load__.bro, line 18: Can't generate broxygen doumentation for redef of Conn::Info, identifier lookup failed`
`warning in /usr/local/bro/lib/bro/plugins/packages/bro-community-id/scripts/./Corelight/CommunityID//__load__.bro, line 19: Can't generate broxygen doumentation for record field community_id, unknown record: Conn::Info`
`error in /usr/local/bro/lib/bro/plugins/packages/bro-community-id/scripts/./Corelight/CommunityID//__load__.bro, line 18: unknown identifier (Conn::Info)`
`error in /usr/local/bro/lib/bro/plugins/packages/bro-community-id/scripts/./Corelight/CommunityID//__load__.bro, line 24: no such field in record (CommunityID::c$conn)`

**Comment by mrdraper** [comment]
I found out that by adding @load site/bro-community-id to the site/local.bro file it did work. 

I don’t know if thats normal, but it works now. :)

**Comment by ckreibich** [comment]
Yeah that makes sense — you have to tell the configuration somewhere that it should load the package. I can't say much regarding the interaction with broctl since I never use it. I'm glad you've figured it out!
